version: '3.8'
services:
  # Service 1: Your Website
  app:
    env_file: .env
    build: .
    ports:
      - "3000:3000" # Maps localhost:3000 to container:3000
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase

  # Service 2: The Database
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db # Persists data so you don't lose it on restart

volumes:
  mongo-data: